### PR TITLE
Add custom tortoise-TTS workflow

### PR DESCRIPTION
**Pull request by gaurangbharti1**
Adding the custom Tortoise-TTS workflow to the Examples repo

### CODE REVIEW

**Comment by mvoodarla** [comment]
With this workflow, I'm assuming the user is forced to enter both `audio1` and `audio2`? Also in the Sieve UI I guess there's currently no way to hint people at what the presets are, which probably would be a nice feature.

**Comment by gaurangbharti1** [comment]
@mvoodarla yep, the user is forced to enter both audio1 and audio2 but they can be the same audio file - it will just lead to worse results. 2 or more files leads to much better output so thought I'd keep it in. And for presets, the `README` mentions what the presets are, but yeah didn't have anywhere else to mention it

**Comment by mvoodarla** [comment]
got it. do you mind reverting it to just take in one audio file for now then? the reason I say this is because while Sieve currently doesn't support optional inputs, it would likely confuse the user if they have to enter multiple pieces of audio.

**Comment by gaurangbharti1** [comment]
@mvoodarla right, I understand, i was thinking of the same thing but needed 2 for the webapp I deployed. Will change it to take in just one. And for the presets - should I keep it as it is right now or just set it to `ultra_fast` and remove the `preset` input field? I wanted to give the user more control but I see how that could be confusing too

**Comment by mvoodarla** [comment]
remove it for now and leave it as an env variable in your code. this is definitely something we need to improve on product soon, to let people create example inputs.

**Comment by gaurangbharti1** [comment]
What exactly do you mean by leave it as an env variable? Like allow the user to run maybe `export tortoise_preset=ultra_fast` and call `preset = os.environ.get("tortoise_preset")` in the code? Would Sieve store that env variable?

**Pull request closed without merging**
